# Generated by Django 2.2.3 on 2019-08-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_history_historyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.Category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='item.Item')),
            ],
        ),
    ]
