# Generated by Django 2.2.3 on 2019-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_delete_categoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='item.Category'),
        ),
    ]
