# Generated by Django 2.2.3 on 2019-08-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='item.Tag'),
        ),
    ]
